# Generated by Django 5.2.4 on 2025-07-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='lasname',
            new_name='lastname',
        ),
    ]
