# Generated by Django 5.2.4 on 2025-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='lasname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='player',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
