# Generated by Django 5.2.4 on 2025-07-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_lasname_player_lastname_player_joined_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='lastname',
            new_name='lasname',
        ),
    ]
