# Generated by Django 5.2.4 on 2025-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_lastname_player_lasname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('joined_date', models.DateField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
