# Generated by Django 5.2.4 on 2025-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_staff_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('coach', models.CharField(max_length=255)),
            ],
        ),
    ]
